# ========== Server ===========
server.port=8080
server.address=0.0.0.0

# ========== Database ===========
spring.datasource.url=jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234567890
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / Hibernate Configuration ===========
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========== Spring Boot Profiles ===========
spring.profiles.active=dev

# Avatar default
comment.avatar=/images/default-avatar.png
