name: Java CI/CD with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests --no-transfer-progress

      - name: Run Unit Tests
        run: mvn test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: blog-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: blog-app

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        env:
          VPS_HOST: 160.250.134.209
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: 160.250.134.209
          VPS_USER: root
          APP_PATH: /root/apps/blog
        run: |
          JAR_FILE=$(ls *.jar)
          echo "Jar file detected: $JAR_FILE"
          ssh $VPS_USER@$VPS_HOST "pkill -f $APP_PATH || true"
          scp $JAR_FILE $VPS_USER@$VPS_HOST:$APP_PATH
          ssh $VPS_USER@$VPS_HOST << EOF
            nohup java -jar $APP_PATH/$JAR_FILE > $APP_PATH/app.log 2>&1 &
          EOF
