name: Java CI with Maven

# Các sự kiện kích hoạt workflow
on:
  push:
    branches:
      - main  # Kích hoạt khi có sự thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Kích hoạt khi có pull request vào nhánh main

jobs:
  # Job build cho ứng dụng Spring Boot
  build:
    runs-on: ubuntu-latest  # Sử dụng hệ điều hành Ubuntu cho job này

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Java JDK (thường dùng JDK 11 cho Spring Boot)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Bước 3: Cài đặt Maven và thực hiện build dự án Spring Boot
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Bước 4: Chạy các unit test để kiểm tra ứng dụng
      - name: Run Tests
        run: mvn test

  # Job deploy cho ứng dụng Spring Boot (tuỳ chọn nếu bạn cần deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Job deploy chỉ chạy nếu job build thành công

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Bước 3: Cài đặt Maven và build lại dự án để tạo bản build (nếu cần)
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Bước 4: Triển khai ứng dụng (ví dụ: nếu sử dụng Heroku hoặc AWS)
      - name: Deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku login -i  # Đăng nhập vào Heroku
          heroku create my-spring-boot-app  # Tạo ứng dụng trên Heroku (nếu chưa có)
          git remote add heroku https://git.heroku.com/my-spring-boot-app.git  # Thêm remote Heroku
          git push heroku main  # Đẩy ứng dụng lên Heroku

