name: Java CI/CD with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests --no-transfer-progress

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: blog-app

      - name: Install SSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: Deploy and Restart App
        env:
          VPS_HOST: 160.250.134.209
          VPS_USER: root
          VPS_PASSWORD: B9TBCyQR~uy
          APP_PATH: /root/apps/blog
          SERVICE_NAME: blog-app
        run: |
          JAR_FILE=$(ls *.jar)
          echo "Jar file detected: $JAR_FILE"

          echo "Uploading JAR to VPS..."
          sshpass -p "$VPS_PASSWORD" scp -o StrictHostKeyChecking=no "$JAR_FILE" "$VPS_USER@$VPS_HOST:$APP_PATH/$SERVICE_NAME.jar"

          echo "Restarting application on VPS..."
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
            set -e
            APP_PATH="$APP_PATH"
            SERVICE_NAME="$SERVICE_NAME"

            PID=\$(pgrep -f "\$APP_PATH/\$SERVICE_NAME.jar" || true)
            if [ -n "\$PID" ]; then
              echo "Stopping old process PID: \$PID"
              kill \$PID
              sleep 3
            fi

            echo "Starting new application..."
            nohup java -jar \$APP_PATH/\$SERVICE_NAME.jar > \$APP_PATH/app.log 2>&1 &
            echo "Application restarted successfully!"
          EOF
