name: Java CI with Maven

on:
  push:
    branches:
      - main  # Kích hoạt khi có sự thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Kích hoạt khi có pull request vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Sử dụng hệ điều hành Ubuntu cho job này

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Java JDK (thường dùng JDK 11 cho Spring Boot)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Thay đổi từ adoptopenjdk thành temurin

      # Bước 3: Cài đặt Maven và thực hiện build dự án Spring Boot
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Bước 4: Chạy các unit test để kiểm tra ứng dụng
      - name: Run Unit Tests
        run: mvn test

  # Job deploy cho ứng dụng Spring Boot lên VPS
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Job deploy chỉ chạy nếu job build thành công

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Thay đổi từ adoptopenjdk thành temurin

      # Bước 3: Cài đặt Maven và build lại dự án để tạo bản build (nếu cần)
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Bước 4: Cài đặt SSH Client để kết nối tới VPS
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Bước 5: Cấu hình SSH với private key từ GitHub Secrets
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 160.250.134.209 >> ~/.ssh/known_hosts  # Thêm địa chỉ IP vào known hosts

      # Bước 6: Triển khai ứng dụng lên VPS qua SSH
      - name: Deploy to VPS
        run: |
          # Di chuyển đến thư mục chứa file jar (hoặc WAR)
          cd target
          # Sao chép file JAR (hoặc WAR) lên VPS
          scp my-spring-boot-app.jar root@160.250.134.209:/path/to/your/app/
          # Đăng nhập SSH vào VPS và khởi động lại ứng dụng
          ssh root@160.250.134.209 'nohup java -jar /path/to/your/app/my-spring-boot-app.jar > /path/to/your/app/app.log 2>&1 &'
