name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run Unit Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        env:
          VPS_HOST: 160.250.134.209
          VPS_USER: root
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: 160.250.134.209
          VPS_USER: root
          APP_PATH: /home/root/apps/blog
          JAR_NAME: my-spring-boot-app.jar
        run: |
          cd target
          scp $JAR_NAME $VPS_USER@$VPS_HOST:$APP_PATH
          ssh $VPS_USER@$VPS_HOST "nohup java -jar $APP_PATH/$JAR_NAME > $APP_PATH/app.log 2>&1 &"
